services:
  web:
    build: .
    image: league-table
    container_name: web
    ports:
      - 8080:80
    environment:
      - LeagueTable_Connection__MySqlConnectionString="Server=mysql; Database=league-table; Uid=db-user; Pwd=db-user-passwd"
  mysql:
    image: mysql:8.1
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=league-table
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-user-passwd
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - db:/data/db
volumes:
  db:

